/**
 * Tool Registry
 *
 * Add a tool by:
 * 1) Creating the tool component under `src/tools/<slug>/...`
 * 2) Adding an entry here (no other code changes required)
 */

const tools = [
  {
    category: 'DevTools',
    group: 'Encoding & Formatting',
    name: 'Base64 Encoder / Decoder',
    slug: 'base64',
    component: 'base64/Base64Tool.jsx',
    description: 'String-first Base64 conversion with UTF-8 safety.',
    keywords: ['base64', 'encode', 'decode'],
  },
  {
    category: 'Data',
    group: 'Formatters',
    name: 'JSON Formatter',
    slug: 'json',
    component: 'json-formatter/JsonFormatterTool.jsx',
    description: 'Format, minify, and validate JSON with worker-based parsing.',
    keywords: ['json', 'format', 'minify', 'validate'],
  },
  {
    category: 'Data',
    group: 'Format Conversion',
    name: 'JSON/XML Converter',
    slug: 'json-xml',
    component: 'json-xml/JsonXmlTool.jsx',
    description: 'Convert between JSON and XML formats.',
    keywords: ['json', 'xml', 'convert'],
  },
  {
    category: 'Data',
    group: 'Format Conversion',
    name: 'JSON/YAML Converter',
    slug: 'json-yaml',
    component: 'json-yaml/JsonYamlTool.jsx',
    description: 'Convert between JSON and YAML formats.',
    keywords: ['json', 'yaml', 'convert'],
  },
  {
    category: 'Data',
    group: 'Format Conversion',
    name: 'JSON/CSV Converter',
    slug: 'json-csv',
    component: 'json-csv/JsonCsvTool.jsx',
    description: 'Convert between JSON arrays and CSV files.',
    keywords: ['json', 'csv', 'convert'],
  },
  {
    category: 'Data',
    group: 'Encoding Conversion',
    name: 'Binary / Hex / Unicode Converter',
    slug: 'encoding-converter',
    component: 'encoding-converter/EncodingConverterTool.jsx',
    description: 'Convert text between binary, hex, and Unicode formats.',
    keywords: ['binary', 'hex', 'unicode', 'encode', 'decode'],
  },
  {
    category: 'Security',
    group: 'JWT Tools',
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    component: 'jwt-decoder/JwtDecoderTool.jsx',
    description: 'Decodes JWT header and payload locally without network calls.',
    keywords: ['jwt', 'token', 'decode'],
  },
  {
    category: 'Security',
    group: 'JWT Tools',
    name: 'JWT Encoder',
    slug: 'jwt-encoder',
    component: 'jwt-encoder/JwtEncoderTool.jsx',
    description: 'Create HS256 JWT tokens from header/payload input.',
    keywords: ['jwt', 'encode', 'hs256', 'token'],
  },
  {
    category: 'Security',
    group: 'JWT Tools',
    name: 'JWT Validator',
    slug: 'jwt-validator',
    component: 'jwt-validator/JwtValidatorTool.jsx',
    description: 'Validate HS256 signatures and expiration claims.',
    keywords: ['jwt', 'validate', 'verify', 'signature'],
  },
  {
    category: 'Security',
    group: 'JWT Tools',
    name: 'JWT Claims Analyzer',
    slug: 'jwt-claims',
    component: 'jwt-claims/JwtClaimsTool.jsx',
    description: 'Analyze JWT time-based claims (exp, nbf, iat).',
    keywords: ['jwt', 'claims', 'exp', 'nbf', 'iat'],
  },
  {
    category: 'Security',
    group: 'Hashing & Encryption',
    name: 'Hash Generator',
    slug: 'hash-generator',
    component: 'hash-generator/HashGeneratorTool.jsx',
    description: 'Generate MD5 and SHA hashes with optional HMAC support.',
    keywords: ['hash', 'sha', 'md5', 'hmac', 'digest'],
  },
  {
    category: 'Security',
    group: 'Hashing & Encryption',
    name: 'AES-GCM Encrypt / Decrypt',
    slug: 'aes-gcm',
    component: 'aes-gcm/AesGcmTool.jsx',
    description: 'Encrypt and decrypt text using AES-GCM keys.',
    keywords: ['aes', 'gcm', 'encrypt', 'decrypt', 'crypto'],
  },
  {
    category: 'Security',
    group: 'Hashing & Encryption',
    name: 'RSA Key Generator',
    slug: 'rsa-keygen',
    component: 'rsa-keygen/RsaKeygenTool.jsx',
    description: 'Generate RSA-OAEP key pairs and export PEM.',
    keywords: ['rsa', 'key', 'pem', 'public', 'private'],
  },
  {
    category: 'Security',
    group: 'Encoding & Formatting',
    name: 'Base32 / Base58 Encoder',
    slug: 'base-encoder',
    component: 'base-encoder/BaseEncoderTool.jsx',
    description: 'Encode or decode Base32/Base58 values.',
    keywords: ['base32', 'base58', 'encode', 'decode'],
  },
  {
    category: 'Security',
    group: 'Encoding & Formatting',
    name: 'HTML Entity Encoder',
    slug: 'html-entities',
    component: 'html-entities/HtmlEntityTool.jsx',
    description: 'Encode and decode HTML entities safely.',
    keywords: ['html', 'entities', 'encode', 'decode'],
  },
  {
    category: 'Security',
    group: 'Password Tools',
    name: 'Password Generator',
    slug: 'password-generator',
    component: 'password-generator/PasswordGeneratorTool.jsx',
    description: 'Generate strong passwords with custom character sets.',
    keywords: ['password', 'generator', 'security', 'strength'],
  },
  {
    category: 'Security',
    group: 'Password Tools',
    name: 'Password Strength Analyzer',
    slug: 'password-strength',
    component: 'password-strength/PasswordStrengthTool.jsx',
    description: 'Estimate password strength, entropy, and improvement tips.',
    keywords: ['password', 'strength', 'entropy', 'analysis'],
  },
  {
    category: 'DevTools',
    group: 'Text Utilities',
    name: 'Case Converter',
    slug: 'case-converter',
    component: 'case-converter/CaseConverterTool.jsx',
    description: 'Convert text into common programming and display casing styles.',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal'],
  },
  {
    category: 'Data',
    group: 'Converters',
    name: 'Number Base Converter',
    slug: 'number-base',
    component: 'number-base-converter/NumberBaseConverterTool.jsx',
    description: 'Translate values between binary, octal, decimal, and hexadecimal.',
    keywords: ['base', 'binary', 'hex', 'octal', 'decimal'],
  },
  {
    category: 'Data',
    group: 'Converters',
    name: 'Timestamp Converter',
    slug: 'timestamp',
    component: 'timestamp-converter/TimestampConverterTool.jsx',
    description: 'Convert between Unix timestamps and human-readable dates.',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time'],
  },
  {
    category: 'Data',
    group: 'Converters',
    name: 'Text ↔ CSV',
    slug: 'text-csv',
    component: 'text-csv/TextCsvTool.jsx',
    description: 'Import a .txt/.csv file and convert between plain text and CSV.',
    keywords: ['csv', 'text', 'import', 'export', 'convert'],
  },
  {
    category: 'Network',
    group: 'URL Tools',
    name: 'URL Encoder / Decoder',
    slug: 'url',
    component: 'url-converter/UrlConverterTool.jsx',
    description: 'Convert strings to URL-safe format and decode them back instantly.',
    keywords: ['url', 'encode', 'decode', 'percent'],
  },
  {
    category: 'Network',
    group: 'URL Tools',
    name: 'URL Inspector',
    slug: 'url-inspector',
    component: 'url-inspector/UrlInspectorTool.jsx',
    description: 'Break down URL structure and query parameters instantly.',
    keywords: ['url', 'inspect', 'query', 'params'],
  },
  {
    category: 'Network',
    group: 'HTTP Tools',
    name: 'API Tester',
    slug: 'api-tester',
    component: 'api-tester/ApiTesterTool.jsx',
    description: 'Simple fetch-based request runner for quick endpoint checks.',
    keywords: ['api', 'http', 'request', 'fetch'],
  },
  {
    category: 'Network',
    group: 'Web Tools',
    name: 'CORS Header Analyzer',
    slug: 'cors-analyzer',
    component: 'cors-analyzer/CorsAnalyzerTool.jsx',
    description: 'Analyze response headers for CORS configuration issues.',
    keywords: ['cors', 'headers', 'security', 'web'],
  },
  {
    category: 'Network',
    group: 'Network Analysis',
    name: 'IP & Subnet Analyzer',
    slug: 'ip-subnet',
    component: 'ip-subnet/IpSubnetTool.jsx',
    description: 'Analyze IPv4 addresses, subnets, and usable ranges.',
    keywords: ['ip', 'subnet', 'cidr', 'network', 'broadcast'],
  },
  {
    category: 'DevTools',
    group: 'Testing',
    name: 'Regex Tester',
    slug: 'regex-tester',
    component: 'regex-tester/RegexTesterTool.jsx',
    description: 'Test expressions against large text with worker-based matching and preview highlights.',
    keywords: ['regex', 'pattern', 'test', 'match'],
  },
  {
    category: 'Forensics',
    group: 'Data Extraction',
    name: 'EXIF / Metadata Viewer',
    slug: 'exif-viewer',
    component: 'exif-viewer/ExifViewerTool.jsx',
    description: 'Extract EXIF and metadata from image files locally.',
    keywords: ['exif', 'metadata', 'image', 'forensics'],
  },
  {
    category: 'Forensics',
    group: 'Text Analysis',
    name: 'Entropy Calculator',
    slug: 'entropy-calculator',
    component: 'entropy-calculator/EntropyCalculatorTool.jsx',
    description: 'Estimate Shannon entropy and character distribution.',
    keywords: ['entropy', 'analysis', 'text', 'forensics'],
  },
  {
    category: 'System',
    group: 'Generators',
    name: 'UUID Generator',
    slug: 'uuid',
    component: 'uuid/UuidGeneratorTool.jsx',
    description: 'Generate RFC 4122 UUID v4 values in lightweight batches.',
    keywords: ['uuid', 'guid', 'generate', 'v4'],
  },
];

export const CATEGORY_ORDER = [
  'Security',
  'Data',
  'Network',
  'Forensics',
  'System',
  'DevTools',
  'Advanced',
];

export default tools;
